import { StatusChip } from "@/components/StatusChip";
import { Mark, Wordmark } from "@/components/Wordmark";
import { Shell } from "@/components/Shell";
import { StatusPanel, ReachPanel } from "@/components/ops/Panels";
import { Quote } from "@/components/ops/Ticker";
const statuses = ["OK", "NEEDS", "URGENT", "UNSURE", "NO_ANSWER", "IN_PROGRESS", "PENDING"] as const;
const counts = { total: 100, OK: 71, NEEDS: 12, URGENT: 9, UNSURE: 4, NO_ANSWER: 3, IN_PROGRESS: 5 };
export default function Kit() {
  return (
    <Shell>
      <div className="mx-auto flex w-full max-w-[1000px] flex-col gap-12 px-4 py-10">
        <section><h2 className="text-[22px] font-extrabold">Marks</h2><div className="mt-3 flex flex-wrap items-end gap-6">{[16, 32, 128].map((s) => <div key={s} className="flex flex-col items-center gap-2"><Mark size={s} /><span className="label">{s}px</span></div>)}<Wordmark /><span className="rounded-md bg-blue px-3 py-2"><Wordmark live /></span></div></section>
        <section><h2 className="text-[22px] font-extrabold">Type</h2><p className="numeral text-[72px] md:text-[120px]">61,672</p><p className="text-[40px] font-extrabold md:text-[56px]">Display 56, Schibsted Grotesk 800</p><p className="text-[16px]">Body 16, Instrument Sans, measure 64ch. Buttons name their result.</p><p className="mono text-[14px]">Mono 14 · 04:12 · $0.0122 · tabular</p><p className="label">label · mono 11 · +0.12em</p></section>
        <section><h2 className="text-[22px] font-extrabold">Stamps and chips</h2><div className="mt-3 flex flex-wrap items-end gap-4">{statuses.map((s) => <span key={s} className={`stamp stamp-${s} text-[34px]`}>{s.replace("_", " ").toLowerCase()}</span>)}</div><div className="mt-3 flex flex-wrap gap-2">{statuses.map((s) => <StatusChip key={s} status={s} />)}</div></section>
        <section><h2 className="text-[22px] font-extrabold">Evidence quote</h2><p className="mt-2 text-[18px]"><Quote text="I'm fine, just a bit light-headed." phrase="light-headed" /></p></section>
        <section><h2 className="text-[22px] font-extrabold">Panels</h2><div className="mt-3 grid max-w-[360px] gap-2"><StatusPanel alert={{ zone: "AZZ544", checkedAt: new Date().toISOString(), active: [], heat: false }} drill={null} zone="AZZ544" town="Maryvale, Phoenix AZ" /><StatusPanel alert={{ zone: "AZZ544", checkedAt: new Date().toISOString(), active: [], heat: true, heatAlerts: [{ event: "Extreme Heat Warning", headline: "" }] }} drill={null} zone="AZZ544" town="Maryvale" /><StatusPanel alert={null} drill={{ id: "x", startedAt: "", completedAt: null, status: "running", trigger: "manual", mode: "simulate", alertId: null, alertEvent: null, alertHeadline: null, total: 100, counts: null, metrics: null, running: true }} zone="AZZ544" town="Maryvale" reached={38} /><ReachPanel counts={counts} metrics={null} reached={92} running /><ReachPanel counts={null} metrics={null} running={false} loading /></div></section>
        <section><h2 className="text-[22px] font-extrabold">Cobalt flip</h2><div className="panel-blue blueprint chalk-grain relative mt-3 p-6"><p className="label text-chalk-muted">the result surface</p><p className="mt-1 text-[28px] font-extrabold">Everything on this surface is chalk on cobalt.</p></div></section>
        <section><h2 className="text-[22px] font-extrabold">Buttons</h2><div className="mt-3 flex flex-wrap gap-3"><button className="btn btn-primary">Declare heat drill</button><button className="btn btn-primary" disabled>Declaring…</button><button className="btn btn-secondary">Mark resolved</button><button className="btn btn-ghost">Reset demo world</button><button className="btn btn-answer btn-lg">Answer the call</button><button className="btn btn-hangup">Hang up</button><span className="inline-flex items-center rounded-md bg-blue px-3"><button className="btn btn-chalk h-8 px-4 text-[14px]">Chalk pill on cobalt</button></span></div></section>
        <section><h2 className="text-[22px] font-extrabold">Inputs</h2><div className="mt-3 flex max-w-sm flex-col gap-2"><input className="input" placeholder="Rosa" /><input className="input" defaultValue="+1415555" aria-invalid="true" style={{ borderColor: "var(--danger)" }} /><p className="text-[13px] text-danger">Enter a US, Canadian, UK or Mexican number in international format.</p></div></section>
        <section><h2 className="text-[22px] font-extrabold">Skeleton, empty, error</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><div className="sk h-20" /><div className="panel p-4 text-center text-ink-muted">No open escalations. Everyone reached said they were fine.</div><div role="alert" className="rounded-md border border-danger/40 bg-danger/10 p-4 text-[14px]">Couldn't reach the API. Showing the last data. <button className="btn btn-secondary ml-2 h-8 px-3 text-[13px]">Retry</button></div></div></section>
      </div>
    </Shell>
  );
}
